### ISSUE TITLE
없는 문서에 접근할 때 편집 화면이 나오는 것 막기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/UnifiedExtensionForFemiwiki#10]
없는 문서로 향하는 링크(일명 "redlink")를 클릭할 경우 바로 편집 화면이 시작되는데, 문서가 아직 없다는 것을 알리는 것이 더 적절해 보입니다.

#### TODO
- [x] redlink 관련 수정 &rarr; https://github.com/femiwiki/UnifiedExtensionForFemiwiki/commit/392c4e7
- [x] revert https://github.com/femiwiki/mediawiki/issues/196 &rarr; https://github.com/femiwiki/mediawiki/commit/d67c3ea
- [x] DiscordNotifications 사용자 가입시 알림 켜기 &raar; https://github.com/femiwiki/mediawiki/commit/d1258f7
- [x] 배포
- [x] [mediawiki:Searchmenu-new](https://femiwiki.com/index.php?title=%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Searchmenu-new&redlink=1&action=edit)의 링크 부분 `[{{fullurl::$1|action=edit}} $1]`으로 수정

#### 참고
- 해당 기능은 초기부터 있다가 RevisionSlider와 호환이 되지 않아 2018년 10월경부터 빠졌었습니다.(https://github.com/femiwiki/skin/commit/25e13f)
- 로그인 한 경우에만 재현 가능합니다.
- 개선요청:[새 문서 만들 때 클릭 수 줄이기](https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Ttk5tho4qcr7dpnb)

**Comment by lens0021** [comment]
Close by https://github.com/femiwiki/femiwiki/commit/63944d3
